image: node:lts-alpine

.setup:
  before_script:
    - sh ci/npm-auth.sh
    - yarn

release:
  image: timbru31/node-alpine-git:latest
  extends: .setup
  stage: deploy
  script:
    - yarn typedoc
    - yarn cov
    - source ci/git-auth.sh
    - git ls-remote
    - sh ci/git-config.sh
    - npm_config_unsafe_perm=true yarn semantic-release
  artifacts:
    paths:
      - public
  only:
    - master
